apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0
  labels:
    app: webapp
    release: "0"
spec:
  containers:
    - name: webapp
      image: richarsonchesterwood/k8s-fleetman-webapp-release-0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0.5
  labels:
    app: webapp
    release: "0.5"
spec:
  containers:
    - name: webapp
      image: richarsonchesterwood/k8s-fleetman-webapp-release-0.5


