apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: myapp
    image: mysql:5
    env:
      - name: MY_SQL_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: fleetman

---

kind: Service
apiVersion: v1
metadata:
  name: database
spec:
  selector:
    name: mysql
  ports:
  - port: 3306
  type: ClusterIP